"""Read-only owner-scoped M6 administration query port."""

from __future__ import annotations

from typing import Protocol
from uuid import UUID

from autplay.domain.admin_views import AdminConfirmationTarget, AdminDashboard, AdminPage
from autplay.domain.web_admin import WebActor


class AdminViews(Protocol):
    def dashboard(self, actor: WebActor) -> AdminDashboard: ...
    def confirmation_target(
        self, actor: WebActor, action: str, target_id: UUID
    ) -> AdminConfirmationTarget: ...
    def audit(self, actor: WebActor, *, limit: int, after: str | None = None) -> AdminPage: ...
    def devices(self, actor: WebActor, *, limit: int, after: str | None = None) -> AdminPage: ...
    def invitations(
        self, actor: WebActor, *, limit: int, after: str | None = None
    ) -> AdminPage: ...
    def sessions(self, actor: WebActor, *, limit: int, after: str | None = None) -> AdminPage: ...
    def jobs(self, actor: WebActor, *, limit: int, after: str | None = None) -> AdminPage: ...
    def imports(self, actor: WebActor, *, limit: int, after: str | None = None) -> AdminPage: ...
    def review(self, actor: WebActor, *, limit: int, after: str | None = None) -> AdminPage: ...
    def vault(self, actor: WebActor) -> object: ...
    def recovery(self, actor: WebActor) -> object: ...
    def diagnostics(
        self, actor: WebActor, *, limit: int, after: str | None = None
    ) -> AdminPage: ...


__all__ = ("AdminViews",)
