"""Short transactional resource-admission operations; adapters never perform network I/O."""

from __future__ import annotations

from datetime import datetime
from types import TracebackType
from typing import Protocol
from uuid import UUID

from autplay.domain.auth import Principal
from autplay.domain.resource_admission import (
    AccountLimits,
    AdmissionStatus,
    IoPermit,
    ResourceAdmission,
    ResourceAuthority,
    ResourceKind,
    ResourceRequest,
    ResourceUsage,
)
from autplay.ports.resource_execution import ResourceExecutionRepository


class ResourceAdmissionRepository(Protocol):
    def lock(self) -> datetime: ...
    def authenticate(self, actor: Principal, now: datetime) -> ResourceAuthority: ...
    def require_authority(self, authority: ResourceAuthority, now: datetime) -> None: ...
    def require_target(
        self,
        authority: ResourceAuthority,
        request: ResourceRequest,
        now: datetime,
    ) -> None: ...
    def require_recording(self, authority: ResourceAuthority, recording_id: UUID) -> None: ...
    def stream_recording(self, authority: ResourceAuthority, audio_variant_id: UUID) -> UUID: ...
    def limits(self, user_id: UUID) -> AccountLimits: ...
    def server_limit(self, kind: ResourceKind) -> int: ...
    def find(self, operation_id: UUID) -> ResourceAdmission | None: ...
    def save(self, operation: ResourceAdmission) -> None: ...
    def waiting_count(self, user_id: UUID, kind: ResourceKind, now: datetime) -> int: ...
    def usage(
        self, authority: ResourceAuthority, kind: ResourceKind, now: datetime
    ) -> ResourceUsage: ...
    def advance(self, now: datetime, maximum: int = 64) -> int: ...
    def status(self, operation: ResourceAdmission, now: datetime) -> AdmissionStatus: ...
    def permits(self, operation_id: UUID, now: datetime) -> tuple[IoPermit, ...]: ...
    def open_permit(
        self, operation: ResourceAdmission, target_id: UUID, now: datetime
    ) -> IoPermit: ...
    def renew_permit(self, permit: IoPermit, now: datetime) -> IoPermit: ...
    def close_permit(self, permit: IoPermit) -> None: ...
    def cleanup(self, now: datetime, maximum: int) -> int: ...


class ResourceAdmissionUnitOfWork(Protocol):
    admissions: ResourceAdmissionRepository
    executions: ResourceExecutionRepository

    def __enter__(self) -> ResourceAdmissionUnitOfWork: ...
    def commit(self) -> None: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        traceback: TracebackType | None,
    ) -> None: ...


class ResourceAdmissionUnitOfWorkFactory(Protocol):
    def __call__(self) -> ResourceAdmissionUnitOfWork: ...
