"""Transactional persistence for account-bound self-service pairing."""

from __future__ import annotations

from datetime import datetime
from types import TracebackType
from typing import Protocol
from uuid import UUID

from autplay.domain.auth import Principal
from autplay.domain.self_device_pairing import (
    PairingAccount,
    PairingBinding,
    PairingCommand,
    PairingIdentity,
    SelfDevicePairing,
)


class SelfPairingRepository(Protocol):
    def find(self, ceremony_id: UUID, *, lock: bool = False) -> SelfDevicePairing | None: ...
    def lock_identity(self, server_id: UUID) -> PairingIdentity: ...
    def lock_account(self, user_id: UUID) -> PairingAccount: ...
    def actor_family(self, actor: Principal, now: datetime) -> UUID: ...
    def require_source(self, ceremony: SelfDevicePairing, now: datetime) -> None: ...
    def require_unique(self, field: str, value: UUID, ceremony_id: UUID) -> None: ...
    def pending_count(self, user_id: UUID, now: datetime) -> int: ...
    def save(self, ceremony: SelfDevicePairing) -> None: ...
    def command(self, operation_id: UUID) -> PairingCommand | None: ...
    def save_command(self, command: PairingCommand) -> None: ...
    def create_binding(self, ceremony: SelfDevicePairing, now: datetime) -> PairingBinding: ...
    def active_binding(self, ceremony: SelfDevicePairing, now: datetime) -> PairingBinding: ...
    def audit(
        self, ceremony: SelfDevicePairing, action: str, operation_id: UUID, now: datetime
    ) -> None: ...
    def rate_gate(self, key: bytes, maximum: int, now: datetime) -> bool: ...
    def cleanup(self, now: datetime, limit: int) -> int: ...


class SelfPairingUnitOfWork(Protocol):
    pairing: SelfPairingRepository

    def __enter__(self) -> SelfPairingUnitOfWork: ...
    def commit(self) -> None: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        traceback: TracebackType | None,
    ) -> None: ...


class SelfPairingUnitOfWorkFactory(Protocol):
    def __call__(self) -> SelfPairingUnitOfWork: ...
