"""Complete PostgreSQL v1 metadata registry and stable inventory constants."""

from __future__ import annotations

from sqlalchemy import MetaData

from .base import Base
from .models import MAPPED_ROWS

metadata: MetaData = Base.metadata

EXPECTED_SCHEMAS: frozenset[str] = frozenset(
    [
        "account",
        "audit",
        "catalog",
        "identity",
        "importing",
        "jobs",
        "library",
        "ml",
        "playlist",
        "sync",
        "vault",
        "wave",
    ]
)
EXPECTED_TABLE_KEYS: tuple[str, ...] = (
    "account.user_account",
    "account.device",
    "account.user_session",
    "catalog.artist",
    "catalog.artist_credit",
    "catalog.artist_credit_name",
    "catalog.work",
    "catalog.recording",
    "catalog.release_group",
    "catalog.release",
    "catalog.medium",
    "catalog.release_track",
    "audit.catalog_change_set",
    "audit.catalog_change_item",
    "audit.audit_event",
    "identity.source_provider",
    "identity.recording_identifier",
    "identity.external_reference",
    "identity.source_observation",
    "identity.matcher_release",
    "identity.calibrator_release",
    "identity.threshold_set",
    "identity.match_policy_activation",
    "identity.recording_redirect",
    "sync.device_event_inbox",
    "sync.sync_event",
    "sync.device_sync_cursor",
    "sync.tombstone",
    "sync.idempotency_record",
    "sync.bootstrap_session",
    "sync.bootstrap_snapshot_item",
    "library.user_interaction_event",
    "jobs.job",
    "jobs.job_attempt",
    "jobs.job_dependency",
    "library.user_track_ref",
    "library.user_track_ref_external_reference",
    "library.library_entry",
    "library.user_track_preference",
    "playlist.playlist",
    "playlist.playlist_entry",
    "playlist.smart_playlist_rule",
    "vault.vault_object",
    "vault.vault_replica",
    "vault.audio_variant",
    "vault.audio_fingerprint",
    "vault.recording_canonical_variant",
    "vault.acquisition_record",
    "vault.upload_session",
    "vault.upload_chunk",
    "importing.import_job",
    "importing.import_entry",
    "identity.match_decision",
    "identity.match_candidate_evidence",
    "ml.embedding_model",
    "ml.recording_embedding",
    "ml.embedding_benchmark_report",
    "ml.embedding_model_activation",
    "ml.enrichment_job",
    "ml.recording_tag_set",
    "ml.recommendation_pipeline_version",
    "ml.recommendation_input_snapshot",
    "ml.recommendation_request",
    "ml.recommendation_item",
    "ml.taste_cluster",
    "ml.taste_cluster_member",
    "ml.offline_recommendation_pack",
    "library.listening_event",
    "wave.room",
    "wave.member",
    "wave.invitation",
    "wave.queue_entry",
    "wave.command",
    "wave.preflight",
    "wave.timing_report",
)
EXPECTED_TABLE_COLUMN_COUNTS: dict[str, int] = {
    "account.user_account": 9,
    "account.device": 11,
    "account.user_session": 8,
    "catalog.artist": 12,
    "catalog.artist_credit": 7,
    "catalog.artist_credit_name": 6,
    "catalog.work": 8,
    "catalog.recording": 16,
    "catalog.release_group": 12,
    "catalog.release": 15,
    "catalog.medium": 10,
    "catalog.release_track": 13,
    "audit.catalog_change_set": 9,
    "audit.catalog_change_item": 8,
    "audit.audit_event": 11,
    "identity.source_provider": 11,
    "identity.recording_identifier": 8,
    "identity.external_reference": 15,
    "identity.source_observation": 8,
    "identity.matcher_release": 7,
    "identity.calibrator_release": 6,
    "identity.threshold_set": 12,
    "identity.match_policy_activation": 11,
    "identity.recording_redirect": 5,
    "sync.device_event_inbox": 18,
    "sync.sync_event": 12,
    "sync.device_sync_cursor": 7,
    "sync.bootstrap_session": 7,
    "sync.bootstrap_snapshot_item": 6,
    "library.user_interaction_event": 11,
    "sync.tombstone": 7,
    "sync.idempotency_record": 8,
    "jobs.job": 25,
    "jobs.job_attempt": 9,
    "jobs.job_dependency": 3,
    "library.user_track_ref": 15,
    "library.user_track_ref_external_reference": 4,
    "library.library_entry": 10,
    "library.user_track_preference": 8,
    "playlist.playlist": 10,
    "playlist.playlist_entry": 11,
    "playlist.smart_playlist_rule": 5,
    "vault.vault_object": 11,
    "vault.vault_replica": 9,
    "vault.audio_variant": 17,
    "vault.audio_fingerprint": 12,
    "vault.recording_canonical_variant": 5,
    "vault.acquisition_record": 9,
    "vault.upload_session": 25,
    "vault.upload_chunk": 6,
    "importing.import_job": 13,
    "importing.import_entry": 16,
    "identity.match_decision": 47,
    "identity.match_candidate_evidence": 15,
    "ml.embedding_model": 28,
    "ml.recording_embedding": 13,
    "ml.embedding_benchmark_report": 10,
    "ml.embedding_model_activation": 10,
    "ml.enrichment_job": 9,
    "ml.recording_tag_set": 12,
    "ml.recommendation_pipeline_version": 9,
    "ml.recommendation_input_snapshot": 10,
    "ml.recommendation_request": 25,
    "ml.recommendation_item": 10,
    "ml.taste_cluster": 8,
    "ml.taste_cluster_member": 4,
    "ml.offline_recommendation_pack": 15,
    "library.listening_event": 15,
    "wave.room": 16,
    "wave.member": 8,
    "wave.invitation": 3,
    "wave.queue_entry": 6,
    "wave.command": 12,
    "wave.preflight": 10,
    "wave.timing_report": 9,
}
EXPECTED_EXPLICIT_INDEX_NAMES: frozenset[str] = frozenset(
    {
        "ix_device_user_active",
        "ix_user_session_user_active",
        "ix_artist_normalized_name_trgm",
        "ix_artist_credit_normalized_name_trgm",
        "ix_artist_credit_name_artist",
        "ix_recording_artist_credit",
        "ix_recording_normalized_title_trgm",
        "ix_release_group_title_trgm",
        "ix_release_release_group",
        "ix_release_barcode",
        "ix_release_track_recording",
        "ix_audit_event_occurred_at",
        "ix_audit_event_target",
        "ix_recording_identifier_lookup",
        "ix_external_reference_recording",
        "ix_source_observation_reference_time",
        "ix_threshold_set_scope",
        "ix_match_policy_activation_threshold_time",
        "ix_device_event_inbox_pending",
        "ix_sync_event_user_sequence",
        "ix_device_sync_cursor_user",
        "ix_tombstone_retention",
        "ix_idempotency_record_expiry",
        "ix_bootstrap_session_expiry",
        "uq_job_idempotency",
        "ix_job_claim",
        "ix_job_expired_lease",
        "uq_user_track_ref_active_recording",
        "ix_user_track_ref_user_status",
        "ix_user_track_ref_external_reverse",
        "uq_library_entry_active",
        "ix_library_entry_page",
        "ix_playlist_owner_active",
        "uq_playlist_entry_active_position",
        "ix_playlist_entry_order",
        "ix_vault_object_status",
        "ix_vault_replica_object_status",
        "ix_audio_variant_recording_valid",
        "ix_audio_fingerprint_candidate",
        "ix_acquisition_record_variant",
        "ix_upload_session_owner_state_time",
        "ix_upload_session_state_expiry",
        "ix_upload_session_computed_sha256",
        "ix_upload_session_job",
        "ix_import_job_user",
        "ix_import_entry_job_status",
        "ix_match_decision_query_time",
        "ix_match_decision_candidate_time",
        "ix_match_decision_matcher_time",
        "ix_match_candidate_evidence_recording",
        "uq_embedding_model_single_active_task",
        "ix_recording_embedding_model_recording",
        "ix_embedding_benchmark_model_time",
        "ix_embedding_activation_task_time",
        "ix_enrichment_job_model_recording",
        "ix_recording_tag_set_model_recording",
        "ix_recommendation_snapshot_user_retention",
        "ix_recommendation_request_user_time",
        "ix_recommendation_item_recording",
        "ix_taste_cluster_user_active",
        "ix_offline_pack_user_device",
        "ix_listening_event_user_time",
        "ix_listening_event_recording_time",
        "ix_wave_room_expiry",
        "ix_wave_member_presence",
        "ix_wave_preflight_room_recording",
    }
)
EXPECTED_COLUMN_COUNT = 841

__all__ = (
    "EXPECTED_COLUMN_COUNT",
    "EXPECTED_EXPLICIT_INDEX_NAMES",
    "EXPECTED_SCHEMAS",
    "EXPECTED_TABLE_COLUMN_COUNTS",
    "EXPECTED_TABLE_KEYS",
    "MAPPED_ROWS",
    "metadata",
)
