"""All 57 typed PostgreSQL persistence rows."""

from __future__ import annotations

from ..base import Base
from .account import (
    DeviceRow,
    UserAccountRow,
    UserSessionRow,
)
from .audit import (
    AuditEventRow,
    CatalogChangeItemRow,
    CatalogChangeSetRow,
)
from .catalog import (
    ArtistCreditNameRow,
    ArtistCreditRow,
    ArtistRow,
    MediumRow,
    RecordingRow,
    ReleaseGroupRow,
    ReleaseRow,
    ReleaseTrackRow,
    WorkRow,
)
from .identity import (
    CalibratorReleaseRow,
    ExternalReferenceRow,
    MatchCandidateEvidenceRow,
    MatchDecisionRow,
    MatcherReleaseRow,
    MatchPolicyActivationRow,
    RecordingIdentifierRow,
    RecordingRedirectRow,
    SourceObservationRow,
    SourceProviderRow,
    ThresholdSetRow,
)
from .importing import (
    ImportEntryRow,
    ImportJobRow,
)
from .jobs import (
    JobAttemptRow,
    JobDependencyRow,
    JobRow,
)
from .library import (
    LibraryEntryRow,
    ListeningEventRow,
    UserTrackPreferenceRow,
    UserTrackRefExternalReferenceRow,
    UserTrackRefRow,
)
from .ml import (
    EmbeddingModelRow,
    OfflineRecommendationPackRow,
    RecommendationItemRow,
    RecommendationRequestRow,
    RecordingEmbeddingRow,
    TasteClusterMemberRow,
    TasteClusterRow,
)
from .playlist import (
    PlaylistEntryRow,
    PlaylistRow,
    SmartPlaylistRuleRow,
)
from .sync import (
    DeviceEventInboxRow,
    DeviceSyncCursorRow,
    IdempotencyRecordRow,
    SyncEventRow,
    TombstoneRow,
)
from .vault import (
    AcquisitionRecordRow,
    AudioFingerprintRow,
    AudioVariantRow,
    RecordingCanonicalVariantRow,
    VaultObjectRow,
    VaultReplicaRow,
)

MAPPED_ROWS: tuple[type[Base], ...] = (
    UserAccountRow,
    DeviceRow,
    UserSessionRow,
    ArtistRow,
    ArtistCreditRow,
    ArtistCreditNameRow,
    WorkRow,
    RecordingRow,
    ReleaseGroupRow,
    ReleaseRow,
    MediumRow,
    ReleaseTrackRow,
    CatalogChangeSetRow,
    CatalogChangeItemRow,
    AuditEventRow,
    SourceProviderRow,
    RecordingIdentifierRow,
    ExternalReferenceRow,
    SourceObservationRow,
    MatcherReleaseRow,
    CalibratorReleaseRow,
    ThresholdSetRow,
    MatchPolicyActivationRow,
    RecordingRedirectRow,
    DeviceEventInboxRow,
    SyncEventRow,
    DeviceSyncCursorRow,
    TombstoneRow,
    IdempotencyRecordRow,
    JobRow,
    JobAttemptRow,
    JobDependencyRow,
    UserTrackRefRow,
    UserTrackRefExternalReferenceRow,
    LibraryEntryRow,
    UserTrackPreferenceRow,
    PlaylistRow,
    PlaylistEntryRow,
    SmartPlaylistRuleRow,
    VaultObjectRow,
    VaultReplicaRow,
    AudioVariantRow,
    AudioFingerprintRow,
    RecordingCanonicalVariantRow,
    AcquisitionRecordRow,
    ImportJobRow,
    ImportEntryRow,
    MatchDecisionRow,
    MatchCandidateEvidenceRow,
    EmbeddingModelRow,
    RecordingEmbeddingRow,
    RecommendationRequestRow,
    RecommendationItemRow,
    TasteClusterRow,
    TasteClusterMemberRow,
    OfflineRecommendationPackRow,
    ListeningEventRow,
)

__all__ = (
    "MAPPED_ROWS",
    "AcquisitionRecordRow",
    "ArtistCreditNameRow",
    "ArtistCreditRow",
    "ArtistRow",
    "AudioFingerprintRow",
    "AudioVariantRow",
    "AuditEventRow",
    "CalibratorReleaseRow",
    "CatalogChangeItemRow",
    "CatalogChangeSetRow",
    "DeviceEventInboxRow",
    "DeviceRow",
    "DeviceSyncCursorRow",
    "EmbeddingModelRow",
    "ExternalReferenceRow",
    "IdempotencyRecordRow",
    "ImportEntryRow",
    "ImportJobRow",
    "JobAttemptRow",
    "JobDependencyRow",
    "JobRow",
    "LibraryEntryRow",
    "ListeningEventRow",
    "MatchCandidateEvidenceRow",
    "MatchDecisionRow",
    "MatchPolicyActivationRow",
    "MatcherReleaseRow",
    "MediumRow",
    "OfflineRecommendationPackRow",
    "PlaylistEntryRow",
    "PlaylistRow",
    "RecommendationItemRow",
    "RecommendationRequestRow",
    "RecordingCanonicalVariantRow",
    "RecordingEmbeddingRow",
    "RecordingIdentifierRow",
    "RecordingRedirectRow",
    "RecordingRow",
    "ReleaseGroupRow",
    "ReleaseRow",
    "ReleaseTrackRow",
    "SmartPlaylistRuleRow",
    "SourceObservationRow",
    "SourceProviderRow",
    "SyncEventRow",
    "TasteClusterMemberRow",
    "TasteClusterRow",
    "ThresholdSetRow",
    "TombstoneRow",
    "UserAccountRow",
    "UserSessionRow",
    "UserTrackPreferenceRow",
    "UserTrackRefExternalReferenceRow",
    "UserTrackRefRow",
    "VaultObjectRow",
    "VaultReplicaRow",
    "WorkRow",
)
